### ISSUE TITLE
Please provide ElectionFactory.json

### ISSUE THREAD

**Issue by shubhamdraval** [schadokar/election-ethereum-react-dapp#2]
Cannot find module './build/ElectionFactory.json'

**Comment by schadokar** [comment]
I guess I forgot to mention the compile step in the readme.
I updated the readme please check.
1. Run the ganache-cli
2. From `ethereum` dir run `node compile.js`. This will create the necessary files.

**Comment by shubhamdraval** [comment]
node compile.js does not create the necessary build folder. Please help.
